limit_req_zone $binary_remote_addr zone=smarthomework_api_limit:10m rate=15r/s;
limit_req_zone $binary_remote_addr zone=smarthomework_login_limit:10m rate=5r/s;
limit_conn_zone $binary_remote_addr zone=smarthomework_conn_limit:10m;
